ALTER TABLE WORKER
ADD FOREIGN KEY (Username) REFERENCES  USERS(Username);
ALTER TABLE WORKER
ADD FOREIGN KEY (IdSpecialty) REFERENCES  SPECIALTY(Id);
ALTER TABLE EMPLOYEE
ADD FOREIGN KEY (Username) REFERENCES  USERS(Username);
ALTER TABLE PROJECT
ADD FOREIGN KEY (IdLocation) REFERENCES  Location(Id);
ALTER TABLE PROJECT
ADD FOREIGN KEY (Client) REFERENCES  USERS(Username);
ALTER TABLE SUPPLIES_ON_PROJECT
ADD FOREIGN KEY (IdSupply) REFERENCES  SUPPLIES(Id);
ALTER TABLE SUPPLIES_ON_PROJECT
ADD FOREIGN KEY (IdStage) REFERENCES  Stage(Id);
ALTER TABLE WORKER_ON_PROJECT
ADD FOREIGN KEY (Username) REFERENCES  USERS(Username);
ALTER TABLE WORKER_ON_PROJECT
ADD FOREIGN KEY (IdStage) REFERENCES  Stage(Id);
ALTER TABLE STAGE
ADD FOREIGN KEY (IdProject) REFERENCES  PROJECT(Id);
ALTER TABLE STAGE
ADD FOREIGN KEY (StageType) REFERENCES  STAGE_TYPE(Id);
ALTER TABLE WORKING_HOURS
ADD FOREIGN KEY (IdStage) REFERENCES  Stage(Id);
ALTER TABLE WORKING_HOURS
ADD FOREIGN KEY (Username) REFERENCES  USERS(Username);
ALTER TABLE BILL_ITEM
ADD FOREIGN KEY (IdBill) REFERENCES  BILL(Id);
ALTER TABLE BILL_ITEM
ADD FOREIGN KEY (IdSuply) REFERENCES  SUPPLIES(Id);