
CREATE TABLE USERS(
	Username VARCHAR(60) NOT NULL,
	Password VARCHAR(60) NOT NULL,
	Telephone INT NOT NULL,
	FirstName VARCHAR(60) NOT NULL,
	LastNameA VARCHAR(60) NOT NULL,
	LastNameB VARCHAR(60) NOT NULL,
	Role VARCHAR(60) NOT NULL, 
	Id INT NOT NULL UNIQUE,
	PRIMARY KEY (Username)
);
CREATE TABLE WORKER(
	Username VARCHAR(60) NOT NULL,
	Code INT NOT NULL,
	IdSpecialty INT NOT NULL,
	PRIMARY KEY (Username)
);
CREATE TABLE EMPLOYEE(
	Username VARCHAR(60) NOT NULL,
	Salary INT NOT NULL,
	PRIMARY KEY (Username)
);
CREATE TABLE SUPPLIES(
	Id SERIAL,
	Name VARCHAR(60) NOT NULL,
	Price INT NOT NULL,
	PRIMARY KEY (Id)
);
CREATE TABLE LOCATION(
	Id SERIAL,
	Province VARCHAR(60) NOT NULL,
	Canton VARCHAR(60) NOT NULL,
	District VARCHAR(60) NOT NULL,
	PRIMARY KEY (Id)
);
CREATE TABLE Specialty(
	Id SERIAL,
	Name VARCHAR(60) NOT NULL UNIQUE,
	PRIMARY KEY(Id)
);
CREATE TABLE SUPPLIES_ON_PROJECT(
	IdSupply INT NOT NULL,
	IdStage INT NOT NULL,
	Quantity INT NOT NULL,
	PRIMARY KEY (IdSupply,IdStage)
);
CREATE TABLE STAGE_TYPE(
	Id SERIAL,
	Name VARCHAR(60) NOT NULL,
	Description TEXT NOT NULL,
	Def BOOLEAN DEFAULT FALSE,
	PRIMARY KEY (Id)
);
CREATE TABLE WORKER_ON_PROJECT(
	Username VARCHAR(60) NOT NULL,
	IdStage INT NOT NULL,
	PRIMARY KEY (Username,IdStage)
);
CREATE TABLE STAGE(
	Id SERIAL,
	StageType INT NOT NULL,
	IdProject INT NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	PRIMARY KEY(Id)
);
CREATE TABLE WORKING_HOURS(
	IdStage INT NOT NULL,
	Username VARCHAR(60) NOT NULL,
	Hours DECIMAL(2) NOT NULL,
	PRIMARY KEY(IdStage, Username)
);
CREATE TABLE BILL(
	Id SERIAL,
	Provider VARCHAR(60) NOT NULL,
	BillPhoto VARCHAR(100) NOT NULL,
	BillNumber INT NOT NULL,
	PRIMARY KEY(Id)
);
CREATE TABLE BILL_ITEM(
	Id SERIAL,
	IdBill INT NOT NULL,
	IdSupply INT NOT NULL,
	Quantity INT NOT NULL,
	PRIMARY KEY(Id)
);
CREATE TABLE PROJECT(
	Id SERIAL,
	Name VARCHAR(60),
	LotArea INT NOT NULL,
	IdLocation INT NOT NULL,
	Rooms INT NOT NULL,
	Restrooms INT NOT NULL,
	Floors INT NOT NULL,
	BuiltArea INT NOT NULL,
	Client VARCHAR(60) NOT NULL,
	PRIMARY KEY (Id)
);

